//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConestogaConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accomodation
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Number_of_Rooms { get; set; }
        public string Rent { get; set; }
        public string Facilities { get; set; }
        public Nullable<bool> PetFriendly { get; set; }
        public Nullable<bool> Parking { get; set; }
        public string Floor { get; set; }
        public Nullable<bool> Furnished { get; set; }
        public Nullable<System.DateTime> Posted_Date { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
        public string Image_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
