//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConestogaConnect.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class AccomodationImage
    {
        public int ImageId { get; set; }
        public string ImageTitle { get; set; }
        public byte[] ImageByte { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> AccomodationId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public HttpPostedFileWrapper ImageFile { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
