//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConestogaConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityInterest
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
