//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConestogaConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingsStatu
    {
        public int Id { get; set; }
        public Nullable<int> MeetingId { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<System.DateTime> AcceptedOn { get; set; }
        public Nullable<System.DateTime> RejectedOn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Meeting Meeting { get; set; }
    }
}
