//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConestogaConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.MeetingsStatus = new HashSet<MeetingsStatu>();
            this.MeetingInterests = new HashSet<MeetingInterest>();
        }
    
        public int Id { get; set; }
        public string MeetingTitle { get; set; }
        public string Description { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> MeetingDateTime { get; set; }
        public string Location { get; set; }
        public Nullable<int> Program { get; set; }
        public Nullable<int> Semester { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UserId { get; set; }
    
        public virtual Program Program1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingsStatu> MeetingsStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingInterest> MeetingInterests { get; set; }
    }
}
