//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConestogaConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.ActivityInterests = new HashSet<ActivityInterest>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public string ActivityName { get; set; }
        public string Description { get; set; }
        public int ActivityTypeId { get; set; }
        public System.DateTime Added_On { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityInterest> ActivityInterests { get; set; }
    }
}
