//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConestogaConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPosting
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string JobPostingNumber { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public string JobType { get; set; }
        public Nullable<double> Salary { get; set; }
        public string Experience { get; set; }
        public string Location { get; set; }
        public string JobSubTitle { get; set; }
        public System.DateTime Posted_Date { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
